### PR TITLE
deepl support source langage korean

### PR DESCRIPTION
**Pull request by yousung**
Due to the official support of Deepl's Korean service,
Add Korean

### CODE REVIEW

**Comment by YiiGuxing** [comment]
Thank you for your PR! 
However, I noticed that you only added Korean to the input language list and did not add it to the target language list. Please confirm if DeepL translator indeed only supports Korean to other languages and does not support translations from other languages to Korean.

**Comment by yousung** [comment]
Thanks for the confirmation.

We've fixed the problem and added
I also tested it.

Thanks for a great plugin.

**Comment by yousung** [comment]
Thanks for the confirmation.

We've fixed the problem and added
I even ran it to check.

Thanks for a great plugin.

**Comment by wonsuc** [comment]
When can this pull requet being merged?

**Comment by wonsuc** [comment]
> @YiiGuxing Thanks for the confirmation.
> 
> We've fixed the problem and added I even ran it to check.
> 
> Thanks for a great plugin.

I guess you also need to fix the `getAdaptedLanguages` function.

**Pull request merged**
