### PR TITLE
New translation dialog

### PR DESCRIPTION
**Pull request by niktrop**
Hello @YiiGuxing ,

I'm working on a new UI for the translation dialog aimed to unify current `TranslationDialog` and `InstantTranslationDialog`. It's based on `InstantTranslationDialog` but with completely new layout and some features ported from `TranslationDialog`. 
image
image
 There is a temporary gray icon on Toolbar and Navigation toolbar to try it. 
image

Gear button currently does nothing, but I want to move relevant settings there from Settings dialog.

I'd like to hear you feedback and discuss further actions.

### CODE REVIEW

**Comment by niktrop** [comment]
@YiiGuxing I've implemented suggested changes, you may try it again.
image

**Comment by YiiGuxing** [comment]
> @YiiGuxing I've implemented suggested changes, you may try it again.
> image

@niktrop I think it's perfect now, thank you very much!

**Comment by niktrop** [comment]
@YiiGuxing Gear button opens the main Translation Settings dialog for now. If you don't mind, I'd like to simplify settings as well in a separate PR.

Also Youdao web translations are appended to the dict viewer. As far as I see this covers the last feature that was available in existing dialogs. Should I go ahead and hide old dialogs from the UI?

**Comment by YiiGuxing** [comment]
@niktrop 

> Gear button opens the main Translation Settings dialog for now. If you don't mind, I'd like to simplify settings as well in a separate PR.

Of course not.

> Also Youdao web translations are appended to the dict viewer. As far as I see this covers the last feature that was available in existing dialogs. Should I go ahead and hide old dialogs from the UI?

Yes, you should.

**Pull request merged**
